### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by pantin21** [einstein95/crunchy-xml-decoder#35] opened 2015-09-17 22:33 UTC
Hi, each time I try to download something I get this error:

![cr downloader error](https://cloud.githubusercontent.com/assets/14338475/9947690/327e09ca-5dd7-11e5-8602-1e24567fbbc2.png)

Can you help me? I'm using the latest version.

**Comment by alzamer2** [comment] 2015-09-18 02:30
I'm not sure 
Did you run make cocki.bat first

**Comment by pantin21** [comment] 2015-09-18 03:02
Yes, I did.

**Comment by alzamer2** [comment] 2015-09-18 12:55
that weird i used the last version with the same link
but i was able to download
did you use "_lxml_crypto_auto_download.bat"? or did you download lxml & crypto manually yourself?

**Comment by pantin21** [comment] 2015-09-18 13:28
I downloaded and installed those two manually. I tried to reinstall them but it didn't change anything.

**Comment by alzamer2** [comment] 2015-09-18 13:32
maybe you used wrong version
uninstall them and try to run "_lxml_crypto_auto_download.bat"

**Comment by pantin21** [comment] 2015-09-18 13:36
Nothing happens when I run the auto download bat, the window disappears immediately.

**Comment by alzamer2** [comment] 2015-09-18 13:41
"_lxml_crypto_auto_download.bat" first try to detected the version Python then if lxml & crypto installed 
if not it download them and install them automatically 
uninstall lxml & crypto from your system (you can manualy delete C:\Python27\Lib\lxml and C:\Python27\Lib\crypto) then run "_lxml_crypto_auto_download.bat"

**Comment by pantin21** [comment] 2015-09-18 13:48
lxml and crypto are removed from my computer.
![python folder](https://cloud.githubusercontent.com/assets/14338475/9960696/26c21876-5e57-11e5-9129-7db5ae286368.png)
The auto download bat still closes immediately without doing anything.

**Comment by alzamer2** [comment] 2015-09-18 14:03
in the folder of crunchy-xml-decoder from "file" click on "open command line" that will open in command line with crunchy-xml-decoder directory then type _lxml_crypto_auto_download.bat 
that will run _lxml_crypto_auto_download.bat without closing even if there is error then post the screen here

**Comment by pantin21** [comment] 2015-09-18 14:08
![cmd crunchy](https://cloud.githubusercontent.com/assets/14338475/9961182/16eaa834-5e5a-11e5-83ac-abf37e2a09c1.png)

**Comment by alzamer2** [comment] 2015-09-18 14:32
if does not work try this one and run start2.bat
https://mega.nz/#!s9FCAAqB!AlqT89MQ-qbOW4BQwTmg28SkwE5aLyjIu0TApzZauEE

**Comment by pantin21** [comment] 2015-09-18 14:37
![cmd start2](https://cloud.githubusercontent.com/assets/14338475/9961952/3c051222-5e5e-11e5-8d3d-ba593e3790ba.png)

**Comment by alzamer2** [comment] 2015-09-18 19:21
i dont know why put it cant get your Python  version 
give me your windows name
32 or 64bit
the name of Python  setup (i know its 2.7 but if you know the its32 or 64 bit say it)
and i will give you download link for Lxml and crypto

**Comment by pantin21** [comment] 2015-09-18 22:29
I had these three installed (and it used to work with an old version but I can't remember when it has started to stop working, maybe the May 14, 2015 update):
- Python 2.7.5 32 bit (http://www.python.org/ftp/python/2.7.5/python-2.7.5.msi)
- lxml 2.6 32 bit for Python 2.7 (https://pypi.python.org/packages/2.7/l/lxml/lxml-3.2.5.win32-py2.7.exe#md5=00536d2ff2b5e9e0b221a936b6fff169)
- crypto 3.2.5 32 bit for Ptyhon 2.7 (https://pypi.python.org/packages/2.7/l/lxml/lxml-3.2.5.win32-py2.7.exe)

**Comment by alzamer2** [comment] 2015-09-18 23:02
if i remember the version of crypto that the script was written with is 2.6 try this one
http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe
side note:it seam that because your system was localized  _lxml_crypto_auto_download.bat did not work i will work on it

**Comment by pantin21** [comment] 2015-09-18 23:17
Oh I'm sorry I messed up with the link and version for crypto on my previous message, it is the one you just gave. I tried to uninstall completely Python for Python 2.7.10 64 bit with the right crypto and lxml, still the same problem whe I try to download a video from Crunchyrol.

**Comment by alzamer2** [comment] 2015-09-19 00:15
why not try from scratch uninstall Python, lxml and crypto and use this
https://www.python.org/ftp/python/2.7.5/python-2.7.5.msi
and this (fix the localized problem-i hope-)
https://mega.nz/#!d4NynRoD!spo4gKdpdyZgFkXMaalC2kChrBRzhaM5_oSRIu21e6c
if you want to try manually
use this
http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe
https://pypi.python.org/packages/2.7/l/lxml/lxml-3.2.5.win32-py2.7.exe#md5=00536d2ff2b5e9e0b221a936b6fff169

**Comment by pantin21** [comment] 2015-09-19 00:24
![cmd crunchy2](https://cloud.githubusercontent.com/assets/14338475/9973552/eb1365b0-5eaf-11e5-8e74-3a0cea3496b7.png)
So the fix seems to make the auto download bat work now, but the error is still here.

**Comment by alzamer2** [comment] 2015-09-19 00:34
nop this error is different this about crypto 
can you run it again i want to see the top something like this
Start up
python directory="C:\Python27\python.exe"
python version=2.7 32Bit
system type=AMD64
Crypto installed
lxml installed

**Comment by pantin21** [comment] 2015-09-19 00:39
![cmd crunchy3](https://cloud.githubusercontent.com/assets/14338475/9973649/0c8c9b06-5eb2-11e5-9275-e94cc8bc0dc9.png)
I think it downloads it everytime I launch _start2.bat or _lxml_crypto_auto_download.bat.

**Comment by alzamer2** [comment] 2015-09-19 00:56
it should not 
tell you what, try this this one i tried and was able to download with Python 2.7 32bit
https://mega.nz/#!0tsnzQyB!X16kUnUa_auiSoBBxlzpQr2izfn6dDl9shIjrzH-sc8

**Comment by pantin21** [comment] 2015-09-19 01:01
![cmd crunchy4](https://cloud.githubusercontent.com/assets/14338475/9973844/5bbe627e-5eb5-11e5-955b-945710e6c432.png)

**Comment by alzamer2** [comment] 2015-09-19 01:16
ok this how it should be
try it

**Comment by pantin21** [comment] 2015-09-19 01:18
![cmd crunchy5](https://cloud.githubusercontent.com/assets/14338475/9973914/c4b851fc-5eb7-11e5-84ee-b30a6c433050.png)
Sorry to bother you with that...

**Comment by alzamer2** [comment] 2015-09-19 01:21
ok i want to try this
delete cookies
and when ask about account press n
lets see what it give

**Comment by pantin21** [comment] 2015-09-19 01:24
![cmd crunchy6](https://cloud.githubusercontent.com/assets/14338475/9973940/90b06380-5eb8-11e5-8c9b-00b8d8028064.png)
![cmd crunchy7](https://cloud.githubusercontent.com/assets/14338475/9973941/9345f0d8-5eb8-11e5-85fb-0d96ebfe9229.png)

**Comment by alzamer2** [comment] 2015-09-19 01:32
well i'm sorry i dont know any more the last one i sent it to you i was able to download 2min preview with it 
i recommended to wait for einstein95 to see where is the problem
last one your windows 8 or 10?

**Comment by pantin21** [comment] 2015-09-19 01:37
Well, thank you for your patience. I'm using Windows 10, but I already had this issue when I still was on Windows 8.1.

I'm currently using the very old version on the darkztar forum with a VPN software to make it work, but it's not really convenient.

**Comment by alzamer2** [comment] 2015-09-19 01:41
mine is Windows 8.1
hmm
i'm sorry again

**Comment by pantin21** [comment] 2015-09-19 01:43
No problem, I can wait Thank you for your hard work.

**Comment by alzamer2** [comment] 2015-09-19 15:01
hi its me again while i was working on the code i got the same error
i want you to try some thing for me
open command line at folder of crunchy-xml-decoder then type
".\crunchy-xml-decoder\ultimate.py"
and input the url when asked

**Comment by pantin21** [comment] 2015-09-19 22:10
![cmd crunchy8](https://cloud.githubusercontent.com/assets/14338475/9978393/9c44a946-5f66-11e5-9470-a348754f8365.png)
Hi, stillt the same error.

**Comment by alzamer2** [comment] 2015-09-19 22:53
wana try to change the windows language to English (maybe the code have localized problem like autodownload)
https://www.youtube.com/watch?v=Zxe3GgNh0QM

**Comment by pantin21** [comment] 2015-09-20 00:12
![cmd crunchy9](https://cloud.githubusercontent.com/assets/14338475/9978645/aeb0991c-5f77-11e5-8a76-4d697e492fba.png)

**Comment by alzamer2** [comment] 2015-09-20 06:56
this rar contain file replace with old one and run then post what you get (the file was modified for the debug)
https://mega.nz/#!9ll3TJBI!RiY4Lv0N43iNwoUvtaukcA5AoEYgeuVA7oD1j8N74Xs

**Comment by pantin21** [comment] 2015-09-20 13:53
![cmd crunchy10](https://cloud.githubusercontent.com/assets/14338475/9981011/5826fc76-5fea-11e5-9dc3-eacea6f0b5b6.png)

**Comment by alzamer2** [comment] 2015-09-24 10:32
hi can you go and download clone from
https://github.com/alzamer2/crunchy-xml-decoder/tree/subtitletag
it has debug function
just add debug after _start2.bat in the command prompt

**Comment by pantin21** [comment] 2015-09-24 22:11
![cmd crunchy11](https://cloud.githubusercontent.com/assets/14338475/10088264/8d5e5156-6354-11e5-86ca-d630c34ac01c.png)

**Comment by alzamer2** [comment] 2015-09-25 12:46
it seam the problem is in windows 10 commands
can you download it again I modified it
https://github.com/alzamer2/crunchy-xml-decoder/tree/subtitletag
just add debug after _start2.bat in the command prompt
oh and there is two file debug.c and debug.p
and can you type this in command prompt I want to check windows 10 commands
help>win10.new.txt
it will generate win10.new.txt can you send it to me

**Comment by MidgardSerpent** [comment] 2015-09-25 13:39
i just did a clean windows 10 (64bit) install on a virtual machine

here is the command prompt output http://pastebin.com/revJF422 also when trying to use _lxml_crypto_auto_download.bat (from your fork) i got this error
![auto downloader](https://cloud.githubusercontent.com/assets/427573/10101840/6ff7d738-63de-11e5-8ed1-ac69904cf13e.PNG)

after installing PyCrypto and lxml manually it worked fine in windows 10 
![screenshot 1](https://cloud.githubusercontent.com/assets/427573/10101871/9e287b94-63de-11e5-98ad-b0f993a4241c.png)

**Comment by pantin21** [comment] 2015-09-25 13:52
http://dl.free.fr/bz21mCabl
I didn't find any debug.p file though, was it supposed to be in the same folder as the debug.c file?

**Comment by alzamer2** [comment] 2015-09-25 15:47
ok I update the fork
https://github.com/alzamer2/crunchy-xml-decoder/tree/subtitletag
let hope it work
can you try it

**Comment by pantin21** [comment] 2015-09-25 23:10
Unfortunately it's still not working.
http://dl.free.fr/ftsJmPMqy

**Comment by alzamer2** [comment] 2015-09-25 23:22
hi try delete the settings.ini

**Comment by alzamer2** [comment] 2015-09-25 23:25
lol
I made some change in code but forget to change the settings.ini
just delete settings.ini and run _start2.bat

**Comment by alzamer2** [comment] 2015-09-25 23:48
how about after you run it once 
you zip the he folder and send it to me (don't forget to delete the cookies)

**Comment by pantin21** [comment] 2015-09-26 00:40
Here's the folder you've asked:
https://mega.nz/#!2RsmGYSL!qlyK6TMk1oTAjM6e0T47hxubojJoiXo6OGrTpDdQpqM

**Comment by alzamer2** [comment] 2015-09-26 10:20
ok I have good news and bad news
the good news
I found where the error happen its happen at pickle.py
the bad news I don't know how to use pickle.py
you need to wait for einstein95 for this one 
and yes the debug was successful

**Comment by pantin21** [comment] 2015-09-26 10:26
Well, I can wait. Thank you very much for everything, you were really patient.

**Comment by einstein95** [comment] 2015-09-27 16:18
Okay, can you try it with the latest master of the main branch, I've made it dump the page html if it can't find the player revision. It doesn't seem to be an issue with the cookies/pickle as I am able to get the page with no cookies sent, but who knows, I'm probably wrong.

**Comment by alzamer2** [comment] 2015-09-27 16:29
hi einstein95
i made pull request can you check it out

**Comment by pantin21** [comment] 2015-09-27 22:44
Hi, thanks for the update.
Now it seems I have another issue:
![cmd12](https://cloud.githubusercontent.com/assets/14338475/10125564/1c93c07a-65b4-11e5-94bb-3fc7f62a3bb5.png)

**Comment by einstein95** [comment] 2015-09-27 22:58
Okay, for some reason or another, Crunchyroll is detecting you to be in
Japan. Try going into crunchyroll.com and scrolling to the bottom, there
should be a flag indicating the current location it's detecting you from.
Are you running any VPN or proxy software either in Windows or in your
browser?

**Comment by pantin21** [comment] 2015-09-27 23:21
I'm currently in Japan. I'm using the hola free VPN in my web browser to be located in USA. I also just tried to use a VPN software to be detected in USA, but it only works with the darkztar forum version.

**Comment by einstein95** [comment] 2015-09-28 11:04
First, It's probably best to not use Hola at all: https://torrentfreak.com/hola-vpn-sells-users-bandwidth-150528/
Second, have you tried another VPN software like SoftEther VPN (http://www.softether.org/)?

**Comment by pantin21** [comment] 2015-09-29 01:20
Well, Hola was really convenient to use... But I thought this crunchy downloader was able to download videos from CR US from another country...

**Comment by einstein95** [comment] 2015-09-29 13:19
Okay,in commit 7e70e800eea1e2896ac1cfeab9556734204e6582 I've added an option in settings.ini that should force a US session. Please try this option.

**Comment by pantin21** [comment] 2015-09-30 00:40
Thank you very much for the update. Now I'm getting this error (I activated the US forcing option):
![cmd crunchy13](https://cloud.githubusercontent.com/assets/14338475/10181784/2fa25b14-6757-11e5-82c5-a32b01968626.png)
I got the same error for every link I tried.

**Comment by alzamer2** [comment] 2015-09-30 06:56
maybe i'm wrong
but at altfuncs.py line 90 you should remove the hash(#)
or replace it with
        if forceusa:
            try:
                session.cookies['sess_id'] = requests.get('http://www.crunblocker.com/sess_id.php').text
            except:
                sleep(10)  # sleep so we don't overload crunblocker
                session.cookies['sess_id'] = requests.get('http://www.crunblocker.com/sess_id.php').text

and "global forceusa" at line 52 i think is better if it before line 16

**Comment by pantin21** [comment] 2015-09-30 07:01
Oh, now it's working!
Thank you very much!

**Comment by alzamer2** [comment] 2015-09-30 07:03
hi this the file with modification
https://mega.nz/#!x4VTXLrJ!E92jxzVNF4nQ6e6e0XI04XsbXEjTepE_uQ84bUDbK10

**Comment by alzamer2** [comment] 2015-09-30 07:07
ohh, congratulation

**Comment by einstein95** [comment] 2015-09-30 07:39
...and I just did that change without seeing alzamer2's replies lol

**Comment by alzamer2** [comment] 2015-09-30 08:12
lol

**Closed** 2015-09-30 08:12 UTC
